#!/bin/sh

# If there are any new ($1) or updated($2) files, update or install
# them.  --force so if we get a partial failure a later update with the
# same version can be installed.

update_OK=$(cat <<-end
                                                    .
                                               u..
                                          upd..
                                      updat..
                                  update..
                             update suc..
    update suc..         update succ..
     update suc..     update succe..
      update suc..  update suces..
       update successful.upda..
        update successful.u.
         update sucessful.
end
)

RED='\033[0;31m'
NC='\033[0m' # No Color



function show_progress()
{
  spinner="\\|/-\\|/-"
  echo -n ' '
  while true;do
    for i in `seq 0 7`; do	  
    echo -n "Applying updates... ${spinner:$i:1}"
    echo -en "\010\010\010\010\010\010\010\010\010\010\010\010\010\010\010\010\010\010\010\010\010"
    sleep 0.25
    done
  done
 }


show_progress &
PID=$!
S1=S2=1
DATE=$(date|tr " " "_")
if [ -n "$1$2" ]; then
    rpm -U --force $1 $2 --quiet >> "/var/log/tuf-$DATE.log" 2>&1
    S1=$?
fi

# If there are any deleted packages, delete them.
if [ -n "$3" ]; then
    rpm -e $3 --quiet >> "/var/log/tuf-$DATE.log" 2>&1
    S2=$?
fi

# We don't need the RPMs any more, so delete them.
rm $1 $2

kill $PID >/dev/null 2>&1

[[ -z $S1  || $S1 -eq 0 ]] && [[ -z $S2 ||  $S2 -eq 0 ]]  && ! [[ -z $S1 && -z $S2  ]] && echo "$update_OK"
echo""

[[ $(wc -l "/var/log/tuf-$DATE.log" |cut -d " " -f1 ) -gt 0 ]] && echo  "NOTE: For WARNINGS/ERRORS please chek: /var/log/tuf-$DATE.log"

exit 0
