[Manifest]
vardir=/var/tuf-manifest
numfile=/var/tuf-manifest/num
repodir=/var/tuf-manifest/metadata
filedir=/var/tuf-manifest/files
url=http://10.0.2.2:8080/tufrepo/metadata
target_url=http://10.0.2.2:8080/tufrepo/targets
filebase=manifest
handler=/usr/lib/tuf-manifest/scripts/tuf-rpm-updater
