#!/bin/sh -e

# If there are any new ($1) or updated($2) files, update or install
# them.  --force so if we get a partial failure a later update with the
# same version can be installed.
if [ -n "$1$2" ]; then
    rpm -U --force $1 $2
fi

# If there are any deleted packages, delete them.
if [ -n "$3" ]; then
    rpm -e $3
fi

# We don't need the RPMs any more, so delete them.
rm $1 $2

exit 0
